### GET Books -  sort ,page
GET localhost:8080/books?sort=name:asc,isbn:desc&take=1&skip=2
Accept: application/json

### GET Books -  sort
GET localhost:8080/books?sort=name:asc,isbn:desc
Accept: application/json

### GET Books -  sort with bad req
GET localhost:8080/books?sort=nameasc
Accept: application/json

### GET Books -  page
GET localhost:8080/books?take=1&skip=2
Accept: application/json

### GET Books  - all
GET localhost:8080/books/
Accept: application/json

### GET Book -  id
GET localhost:8080/books/1
Accept: application/json

### Delete Book
DELETE localhost:8080/books/1
Accept: application/json

### Send POST
POST localhost:8080/books/
Content-Type: application/json

{
  "name": "book",
  "isbn": "800-05-05",
  "author": "Test",
  "releaseDate": "2022-05-05"
}

### Send GET
GET localhost:8080/books/5
Content-Type: application/json

### Send PUT
PUT localhost:8080/books/
Content-Type: application/json

{
  "id" : 1,
  "name": "book12",
  "isbn": "800-05-05-05",
  "author": "Test12",
  "releaseDate": "2022-05-05"
}